### ISSUE TITLE
[Bug]: installing npm for starting the project

### ISSUE THREAD

**Issue by JacobeMNA** [codeSTACKr/create-10k-nft-collection#130]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

I tried running ( npm install ) and error happen

### What have you tried?

I report issues and somebody tried to help me but I think he can't and direct me to here and told me come and my report issue here...

the guy also give me some way to try but it didn't worked.

### Relevant log output

```shell
npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer     
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d 
/s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r901912! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/901912/chrome-win.zip
npm ERR!     at C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:367:27   
npm ERR!     at ClientRequest.requestCallback (C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\node_modules\puppeteer-extra-plugin-adblocker\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserFetcher.js:493:13)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:526:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:482:22)
npm ERR!     at TLSSocket.emit (node:events:526:28)
npm ERR!     at addChunk (node:internal/streams/readable:315:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mahdi\AppData\Local\npm-cache\_logs\2022-03-23T10_16_15_836Z-debug-0.log
```

### Protect your information

- [X] I Agree

**Comment by JacobeMNA** [comment]
when I try running ( npm run generate ) after it, this error happen.


> 10k-collection-video@2.0.0 generate
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0/node_modules/sha1'
Require stack:
- C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\src\main.js
- C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Mahdi\Downloads\create-10k-nft-collection-2.0.0\src\main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mahdi\\Downloads\\create-10k-nft-collection-2.0.0\\src\\main.js',
    'C:\\Users\\Mahdi\\Downloads\\create-10k-nft-collection-2.0.0\\index.js'
  ]
}

what I suppose to do for reaching the next step

**Comment by Barbo91** [comment]
Thanks for the great job of this project, i had the same problem try to move to program away from download folder, make sure nodejs is running and when u launch npi install command wait 5 minutes and let visual studio do his things. Check ur internet connection too.

**Comment by Barbo91** [comment]
Thanks for the great job of this project, i had the same problem try to move to program away from download folder, make sure nodejs is running and when u launch npi install command wait 5 minutes and let visual studio do his things. Check ur internet connection too.

**Comment by sanurainakamoto** [comment]
hello i had same problem and i know you tried what i'm going to say and it didn't work. but when i turned off my proxy i had been able to install npm

**Comment by valenticoder** [comment]
Hey bro, have you solved the problem ? I am facing the same problem rn. I tries turning off my proxy, changed from the download folder but nothing has changed... have you solved?

**Comment by DomDom007** [comment]
I had the same problem, I copied the files in the folder in another new folder and it worked
