### ISSUE TITLE
[Bug]: ENOENT: no file or directory. I've tried everything. Layers copied, layers dropped, no non-alpha-numeric hyphens or some such, deleting  the package-lock.json file and reinstalling, nothing seems to work

### ISSUE THREAD

**Issue by graaff17** [codeSTACKr/create-10k-nft-collection#132]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened!

### What have you tried?

Draging, copying layers
Reinstalling code, rebooting, moving to public folder, checking all .png files, deleting package-lock file and reinstalling, The file points to the right path. 

### Relevant log output

```shell
> 10k-collection-video@2.0.0 generate
> node index.js

(node:5956) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1392
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/bh/Public/Armadillo/layers/Background/'
    at Object.readdirSync (node:fs:1392:3)
    at getElements (/Users/bh/Public/Armadillo/src/main.js:73:6)
    at /Users/bh/Public/Armadillo/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/bh/Public/Armadillo/src/main.js:87:30)
    at startCreating (/Users/bh/Public/Armadillo/src/main.js:352:20)
    at /Users/bh/Public/Armadillo/index.js:6:3
    at Object.<anonymous> (/Users/bh/Public/Armadillo/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/bh/Public/Armadillo/layers/Background/'
```

### Protect your information

- [X] I Agree

**Comment by graaff17** [comment]
No sorry that doesn't work.
