### ISSUE TITLE
[Bug]: Error: Cannot find module 

### ISSUE THREAD

**Issue by eternalquantum** [codeSTACKr/create-10k-nft-collection#134]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened!

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.
I have tried Reinstalling code, rebooting, moving to public folder, checking all .png files, deleting package-lock file and reinstalling, The file points to the right path.

### Relevant log output

```shell
PS C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0> npm run generate

> 10k-collection-video@2.0.0 generate
> node index.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\node_modules\canvas\lib\bindings.js      
- C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\node_modules\canvas\lib\canvas.js        
- C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\node_modules\canvas\index.js
- C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\src\main.js
- C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\USER\Desktop\create-10k-nft-collection-2.0.0\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
    'C:\\Users\\USER\\Desktop\\create-10k-nft-collection-2.0.0\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\USER\\Desktop\\create-10k-nft-collection-2.0.0\\node_modules\\canvas\\lib\\canvas.js',
    'C:\\Users\\USER\\Desktop\\create-10k-nft-collection-2.0.0\\node_modules\\canvas\\index.js',
    'C:\\Users\\USER\\Desktop\\create-10k-nft-collection-2.0.0\\src\\main.js',
    'C:\\Users\\USER\\Desktop\\create-10k-nft-collection-2.0.0\\index.js'
  ]
}

Node.js v17.7.1
```

### Protect your information

- [X] I Agree

**Comment by Angelje47** [comment]
Happen something like that elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % npm run generate

> 10k-collection-video@2.0.0 generate
> node index.js

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/sha1'
Require stack:
- /Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/src/main.js
- /Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/src/main.js:4:14)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/src/main.js',
    '/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/index.js'
  ]
}

Node.js v18.7.0
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % npm i
npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest
npm ERR! code 1
npm ERR! path /Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas
npm ERR! command failed
npm ERR! command sh /var/folders/nm/29lr46tj22xfnms_m_w7ch300000gn/T/install-da7db7ed.sh
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.6
npm ERR! node-pre-gyp info using node@18.7.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@18.7.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v108-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.7.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.7.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/elsygarcia/Library/Caches/node-gyp/18.7.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/elsygarcia/Library/Caches/node-gyp/18.7.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/elsygarcia/Library/Caches/node-gyp/18.7.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/elsygarcia/Downloads/create-10k-nft-collection-2.0.0/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v18.7.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.6
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsygarcia/.npm/_logs/2022-08-18T16_44_16_064Z-debug-0.log
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % npm install --global yarn
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/yarn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/yarn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsygarcia/.npm/_logs/2022-08-18T16_48_51_042Z-debug-0.log
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % npm install --global yarn
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/yarn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/yarn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsygarcia/.npm/_logs/2022-08-19T21_19_41_377Z-debug-0.log
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % /Applications/hashlips-art-engine-app.app
zsh: no such file or directory: /Applications/hashlips-art-engine-app.app
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 % npm install --global yarn
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/yarn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/yarn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/yarn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsygarcia/.npm/_logs/2022-08-19T21_36_22_169Z-debug-0.log
elsygarcia@MacBook-Air-de-ELSY create-10k-nft-collection-2.0.0 %
