### ISSUE TITLE
[Bug]: Error: ENOENT: no such file or directory, scandir 'C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0/layers/Eyeball/'

### ISSUE THREAD

**Issue by ADRIhein2** [codeSTACKr/create-10k-nft-collection#142]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

Hi, i am a beginner, i have this issue but could not find a solution.

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
PS C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0> npm run generate

> 10k-collection-video@2.0.0 generate C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0
> node index.js

(node:20272) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0/layers/Eyeball/'
    at Object.readdirSync (fs.js:1047:3)
    at getElements (C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\src\main.js:73:6)
    at C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\src\main.js:89:15
    at layersSetup (C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\src\main.js:87:30)
    at startCreating (C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\src\main.js:352:20)
    at C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\index.js:6:3
    at Object.<anonymous> (C:\Users\PC\Desktop\create-10k-nft-collection-2.0.0\index.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Protect your information

- [X] I Agree

**Comment by awiswasi** [comment]
Try this:
`npm rebuild node-fetch`
Let me know if it works.

**Comment by samdupnamgyal** [comment]
still not working same problem for me

**Comment by awiswasi** [comment]
> still not working same problem for me

Can you check if you have the folder `Eyeball`  ? It looks like its trying to access it but the path doesn't exist.
This happened to me before when I changed some folders and item names, and then forgot about them.

**Comment by nyjfootball22** [comment]
errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/michaelsimoni/Downloads/create-10k-nft-collection-2.0.0/layers/Eyeball/'
}

Ive relabled all files. Ive deleted everything and redownload it all. If found the eyeball file and deleted it fully and tried starting from scratch. No matter what I tried I keep getting this error.

**Comment by nyjfootball22** [comment]
I figured it out. After unzipping the file i had to go in and replace the layers .png files and went into the config and changed the layer order to my specific order.
