### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tkearl11** [codeSTACKr/create-10k-nft-collection#148]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

Getting the following error.... any ideas?

Error: ENOENT: no such file or directory, scandir '/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/build/genericJson'
    at Object.readdirSync (node:fs:1392:3)
    at main (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:24:20)
    at main (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:80:5)
    at Object.<anonymous> (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:84:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/build/genericJson'

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
Error: ENOENT: no such file or directory, scandir '/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/build/genericJson'
    at Object.readdirSync (node:fs:1392:3)
    at main (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:24:20)
    at main (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:80:5)
    at Object.<anonymous> (/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/utils/nftport/uploadMetas.js:84:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/troysdk/Documents/MYBLOX/Collection Builder/create-10k-nft-collection-2.0.0/build/genericJson'
```

### Protect your information

- [X] I Agree

**Comment by masterolive** [comment]
Same here. 

Running the generator throws up the same error but in my case, it's looking for the tutorial folders. Ive replaced the layers with my own in the layer folder, renamed the layers in src/config.js line 13, and refreshed the explorer. 

Still get the error:


masterolive@Andres-MBP create-10k-nft-collection-2.0.0 % npm run generate

> 10k-collection-video@2.0.0 generate
> node index.js

(node:13351) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/layers/Eye color/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:73:6)
    at /Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:87:30)
    at startCreating (/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:352:20)
    at /Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/index.js:6:3
    at Object.<anonymous> (/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/masterolive/Desktop/NFT/Github/create-10k-nft-collection-2.0.0/layers/Eye color/'
}


Using Intel Based Mac
