### ISSUE TITLE
[Bug]: Installation vulnerabilities and failure to generate images (stuck scanning demo content path despite being removed) | errno: -2, | syscall: 'scandir' | code: 'ENOENT'

### ISSUE THREAD

**Issue by masterolive** [codeSTACKr/create-10k-nft-collection#171]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

1. Installation shows vulnerabilities, 

2. Unable to generate personal NFTs. The program will successfully generate a build for the demo layers and default config, but the generator will not successfully run with new content. It seems like the program will not register the changes in the layers folder or updated config.js when the contents are replaced and updated accordingly, instead it continues to look for the demo directory and fails.

### What have you tried?

All Steps:

- Installed node js, the current version is 16.15.0 - success 

-Unpacked repo, opened new folder via VS code, and installed dependencies via VS Code. - Partial Sucess
(Received message of  4 vulnerabilities 3 high 1 critical - See Log output) Able to still continue demo generation. 

- Attempt npm run generate with demo layers - Success. 

- Delete contents under the layers folder, and click and drag new folder and contents into the layer folder. - Success 

-Edit config.js accordingly:
Line 9 -Name
Line 10 -Description
Line 16 Layer order and layer folder names.
-Sucess

- Format configured 

-Extra metadata was removed exactly as performed in the video: 
(Latest ULTIMATE ver: https://www.youtube.com/watch?v=quGdJweadFM&t=0s)

-Attempt to run 2nd generator, but the attempt fails. - FAIL

The error indicates no directory exists, pointing to the original demo folder, unable to read/register the updated layers in the Layers folder and layer info in config.js (See Log output) and new NFTs cannot be generated.

This error comes up for both MAC OS and WINDOWS (I attempted the process on both machines)

Attempted to scan main.js for incorrect "  '  " 's and replace them with  "  `  " 's - none found, brackets appear to be correct.

I Googled and searched GitHub issues, and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
Installation Message: 

`masterolive@Andres-MBP create-10k-nft-collection-2.0.0 % node -v
v16.15.0
masterolive@Andres-MBP create-10k-nft-collection-2.0.0 % npm i
npm WARN deprecated puppeteer@10.4.0: Version no longer supported. Upgrade to @latest

added 165 packages, and audited 166 packages in 8s

5 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 high, 1 critical)

To address all issues, run:
  npm audit fix`


Generator error message: 


`> 10k-collection-video@2.0.0 generate
> node index.js

(node:14969) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/layers/Eye color/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:73:6)
    at /Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:87:30)
    at startCreating (/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/src/main.js:352:20)
    at /Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/index.js:6:3
    at Object.<anonymous> (/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/masterolive/NFT/Github/create-10k-nft-collection-2.0.0/layers/Eye color/'
}`
```

### Protect your information

- [X] I Agree

**Comment by masterolive** [comment]
Oof I didn't save file. 

Lord help us all.
