### ISSUE TITLE
[Bug]: error -4058

### ISSUE THREAD

**Issue by huzaifahchaudhry** [codeSTACKr/create-10k-nft-collection#177]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

error in npn run generate comand

### What have you tried?

relabeled all files, double checked names,uninstalled node-fetch.. installed fetch@2.....tried  puppeteer and puppeteer-core. still isnt generating my files tho all a are png and had worked on a previous proj.

### Relevant log output

```shell
Error: ENOENT: no such file or directory, scandir 'C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0/layers/Eyeball/'
    at Object.readdirSync (node:fs:1405:3)
    at getElements (C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\src\main.js:73:6)
    at C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\src\main.js:87:30)
    at startCreating (C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\src\main.js:352:20)
    at C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\index.js:6:3
    at Object.<anonymous> (C:\Users\Dell\Desktop\create-10k-nft-collection-2.0.0\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\Dell\\Desktop\\create-10k-nft-collection-2.0.0/layers/Eyeball/'
}
```

### Protect your information

- [X] I Agree

**Comment by wogalf** [comment]
I had the same error, removing all the special characters(', ", -, _, ,, etc) from the layer's name worked for me. Just use letters, numbers and # for the rarity

**Comment by huzaifahchaudhry** [comment]
thanks man...appreciated🤝
