### ISSUE TITLE
Cannot read properties of undefined (reading 'edition')

### ISSUE THREAD

**Issue by jones0770** [codeSTACKr/create-10k-nft-collection#54]
![dddddda](https://user-images.githubusercontent.com/85363653/149917368-19aa48cb-1e99-45e4-bad6-d189413d4d87.JPG)

**Comment by zanniefresh** [comment]
I'm also facing this same error today..hopefully he can come through and help

**Comment by trafaon** [comment]
I have the same error

PS C:\Users\user\Downloads\nft\video-source-code-create-nft-collection> node utils/nftport/mint.js 
C:\Users\user\Downloads\nft\video-source-code-create-nft-collection\utils\nftport\mint.js:22
    const mintFile = `${basePath}/build/minted/${meta.custom_fields.edition}.json`;
                                                                    ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at main (C:\Users\user\Downloads\nft\video-source-code-create-nft-collection\utils\nftport\mint.js:22:69)  
    at Object.<anonymous> (C:\Users\user\Downloads\nft\video-source-code-create-nft-collection\utils\nftport\mint.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
PS C:\Users\user\Downloads\nft\video-source-code-create-nft-collection>

**Comment by MintPunk** [comment]
Same Problem . waiting...

**Comment by codeSTACKr** [comment]
Seems like you .json file is malformed and is missing the `edition` property. You will need to backtrack to find the source of the issue.
