### ISSUE TITLE
Issue updating the IPFS links

### ISSUE THREAD

**Issue by DanWithy** [codeSTACKr/create-10k-nft-collection#56]
I have used npm uninstall node-fetch and npm install node-fetch@2 but when I type node utils/nftport/uploadFiles.js I get 

D:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js:10
formData.append("file", fileStream);
                        ^

ReferenceError: fileStream is not defined
    at D:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js:10:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadFiles.js:7:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Any help would be very helpful!

**Comment by thepeanutgalleryandco** [comment]
You can try to use my repo as well - https://github.com/thepeanutgalleryandco/create-and-mint-nft-collection - It is based on Hashlips and codeSTACKr repo, with a few fixes.

**Comment by veldhaenchen** [comment]
did you followed the video and missed initializing formData? `const FormData = require("form-data");`

**Comment by codeSTACKr** [comment]
be sure your code matches the source code in this repo
