### ISSUE TITLE
Won't let me run npm generate because of a missing layer?

### ISSUE THREAD

**Issue by raresvladd** [codeSTACKr/create-10k-nft-collection#64]
Hi, so I can't run npm generate because I don't have a layer called "Eyelids" in my layers file, but my collection doesn't have any layer called "Eyelids" it's the default file that had it. 

Here's the code error: 
Error: ENOENT: no such file or directory, scandir 'C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0/layers/Eyeball/'   
    at Object.readdirSync (node:fs:1390:3)
    at getElements (C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\src\main.js:73:6)
    at C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\src\main.js:89:15
    at Array.map (<anonymous>)
    at layersSetup (C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\src\main.js:87:30)
    at startCreating (C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\src\main.js:351:20)
    at C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\index.js:6:3
    at Object.<anonymous> (C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',

**Comment by Blaette** [comment]
I got the same error

**Comment by veldhaenchen** [comment]
> ENOENT: no such file or directory, scandir 'C:\Users\44798\OneDrive\Desktop\video-source-code-create-nft-collection-1.1.0/layers/Eyeball/'

Your error says something else

Eyeball !== Eyelids

also this repo does not contain 'Eyelids' anywhere. If you like to add an extra layer then simply create a folder inside your Layers directory and make sure to add it to your collections config.

**Comment by codeSTACKr** [comment]
This is not an issue with the code base. You may have a special character such as a dash or hyphen in either your layer folder or file names.

**Comment by Blaette** [comment]
Save your changes in the config.js file.
All worked after I saved the new layer commands ^^

**Comment by raresvladd** [comment]
> Save your changes in the config.js file. All worked after I saved the new layer commands ^^

Thanks a lot, mate
