### ISSUE TITLE
syntax error : invalid or unexpected token

### ISSUE THREAD

**Issue by Mohammadkhare** [codeSTACKr/create-10k-nft-collection#74]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

i dont know whats problem
![Screenshot (1964)](https://user-images.githubusercontent.com/98826101/151987591-4c9f52e9-c830-4a29-a3af-1f03afa09f1f.png)

### What have you tried?

just reading the error

### Protect your information

- [X] I Agree

**Comment by codeSTACKr** [comment]
That isn't the entire error. Please add more context. What command are you trying to run?

**Comment by ei9h7** [comment]
I'm getting a similar error. I was able to fix it for uploading the image files/updating jsons... but when I run the uploadMetas.js script I get this  error. Hopefully this information helps add to the OPs error information:

`05:22 $ node utils/nftport/uploadMetas.js
undefined:1



SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at main (/Users/ei9h7/projects/NFTS/woman-by-tatyana-bogdanova/nft-automate/utils/nftport/uploadMetas.js:24:27)
    at Object.<anonymous> (/Users/ei9h7/projects/NFTS/woman-by-tatyana-bogdanova/nft-automate/utils/nftport/uploadMetas.js:56:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.4.0`

**Comment by Mohammadkhare** [comment]
> That isn't the entire error. Please add more context. What command are you trying to run?

I was trying to run uploadFiles.js (node utils/nftport/uploadFiles.js) but this error apeared.

**Comment by Mohammadkhare** [comment]
> That isn't the entire error. Please add more context. What command are you trying to run?

Error: Cannot find module 'E:\utils\nftport\uploadFiles.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
