### ISSUE TITLE
[Bug]: npm run generate

### ISSUE THREAD

**Issue by Arimay1234** [codeSTACKr/create-10k-nft-collection#76]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened! When I type the grow edition size to 100 and when I typed npm run generate, some amount of pictures get created but not full. It stops in the middle immediately and gives this message:

The error message:

const image = await loadImage(${_layer.selectedElement.path});
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:180:10)
    at C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Note: all my scripts are correct too!

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution. Also I tried proofreading the scripts which were all right, but no help.

### Relevant log output

```shell
const image = await loadImage(${_layer.selectedElement.path});
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:180:10)
    at C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Admin\Desktop\hash111\hashlips_art_engine-1.1.1_update\src\main.js:360:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Protect your information

- [X] I Agree

**Comment by Lowkeydro** [comment]
Hey I’m having a similar problem but I’m not even getting the to download in build folder I get at Array.Map (<Anonymous>) not sure why!

**Comment by gohias** [comment]
I'm getting the same problem and the scripts are correct.
TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Admin\Documents\create-10k-nft-collection-main\src\main.js:184:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Admin\Documents\create-10k-nft-collection-main\src\main.js:183:10)    at C:\Users\Admin\Documents\create-10k-nft-collection-main\src\main.js:364:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Admin\Documents\create-10k-nft-collection-main\src\main.js:363:17
