### ISSUE TITLE
[Bug]: ReferenceError: extraMetadata is not defined

### ISSUE THREAD

**Issue by hamadalrumaihi** [codeSTACKr/create-10k-nft-collection#77]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened! i tried the generate order but then this comes out

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
ReferenceError: extraMetadata is not defined
    at Object.<anonymous> (C:\Users\hr\OneDrive\Desktop\create-10k-nft-collection-main\src\config.js:111:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\hkalr\OneDrive\Desktop\create-10k-nft-collection-main\src\main.js:24:5)   
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
PS C:\Users\hr\OneDrive\Desktop\create-10k-nft-collection-main> npm run generate
```

### Protect your information

- [X] I Agree

**Comment by thepeanutgalleryandco** [comment]
@hamadalrumaihi in your config.js file, do you have an extraMetadata object? You should have an empty object or an object with items in it for the scripts to work.

**Comment by hamadalrumaihi** [comment]
> 

i had it in the main src but looking through the config right now

**Comment by hamadalrumaihi** [comment]
> @hamadalrumaihi in your config.js file, do you have an extraMetadata object? You should have an empty object or an object with items in it for the scripts to work.

hahha it worked thanks :) 

it was wayyydown below the code
