### ISSUE TITLE
uploadFiles.js looking for a non-existent file named .DS_Store.json

### ISSUE THREAD

**Issue by dgsmith7** [codeSTACKr/create-10k-nft-collection#87]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

(node:20869) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/dgsmith7/Documents/Computation/create-10k-nft-collection-main/build/json/.DS_Store.json'A bug happened!

### What have you tried?

I tried creating the file and leaving it empty but it still fails.

### Relevant log output

```shell
David-Smiths-MacBook-Pro-3:create-10k-nft-collection-main dgsmith7$ node utils/nftport/uploadFiles.js
.DS_Store
(node:20869) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/dgsmith7/Documents/Computation/create-10k-nft-collection-main/build/json/.DS_Store.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at main (/Users/dgsmith7/Documents/Computation/create-10k-nft-collection-main/utils/nftport/uploadFiles.js:20:23)
    at Object.<anonymous> (/Users/dgsmith7/Documents/Computation/create-10k-nft-collection-main/utils/nftport/uploadFiles.js:43:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
David-Smiths-MacBook-Pro-3:create-10k-nft-collection-main dgsmith7$ node --trace-warnings ...
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/dgsmith7/Documents/Computation/create-10k-nft-collection-main/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Protect your information

- [X] I Agree

**Comment by dgsmith7** [comment]
I think it is just a silly Mac OS thing.  I just put most of the loop into a conditional statement telling it to ignore any '.DS_Store' filename and it seems to be working now.:

  for (const file of files) {
    const fileName = path.parse(file).name;
    if (fileName !== '.DS_Store' ) {
    console.log(fileName);
    let jsonFile = fs.readFileSync(`${basePath}/build/json/${fileName}.json`);
    let metaData = JSON.parse(jsonFile);
    if(!metaData.file_url.includes('https://')) {
      const response = await fetchWithRetry(file);
      metaData.file_url = response.ipfs_url;
  
      fs.writeFileSync(
        `${basePath}/build/json/${fileName}.json`,
        JSON.stringify(metaData, null, 2)
      );
      console.log(`${response.file_name} uploaded & ${fileName}.json updated!`);
    } else {
      console.log(`${fileName} already uploaded.`);
    }

    allMetadata.push(metaData);
  }
  }
  fs.writeFileSync(
    `${basePath}/build/json/_metadata.json`,
    JSON.stringify(allMetadata, null, 2)
  );
}
